import { defineType, defineField } from 'sanity';

export const blogPost = defineType({
  name: 'blogPost',
  title: 'Blog Post',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Name',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'name' },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'metaTitle',
      title: 'Meta Title',
      type: 'string',
    }),
    defineField({
      name: 'metaDescription',
      title: 'Meta Description',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'thumbnail',
      title: 'Thumbnail',
      type: 'image',
      options: { hotspot: true },
      fields: [
        defineField({
          name: 'alt',
          title: 'Alt Text',
          type: 'string',
        }),
      ],
    }),
    defineField({
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      rows: 3,
      description: 'Short subtitle shown below the H1 and used in cards. ~140-160 chars.',
    }),
    defineField({
      name: 'directAnswer',
      title: 'Direct Answer (TL;DR)',
      type: 'text',
      rows: 4,
      description: 'The AEO citation surface — a self-contained 40-60 word direct answer block rendered above the body content. Marked with Speakable schema for AI engine extraction. Keep tight: this is what ChatGPT, Perplexity, Claude, and Google AI Overviews will quote.',
    }),
    defineField({
      name: 'content',
      title: 'Content',
      type: 'text',
      description: 'Rich text content stored as HTML',
      // Guard against the duplicate-FAQ bug first seen 2026-05-26 on the
      // LLM SEO listicle. The page template renders the `faq` array as
      // its own FAQ section. If the body content ALSO contains an inline
      // "Frequently Asked Questions" H2, readers see the FAQ twice.
      // This validator surfaces the conflict in Studio AND on any API
      // mutation that goes through Sanity's validation layer.
      validation: (rule) =>
        rule.custom((content, context) => {
          if (typeof content !== 'string' || !content) return true;
          const inlineFaqPattern =
            /<h2[^>]*>\s*(?:FAQ|FAQs|Frequently\s+Asked\s+Questions?|Common\s+Questions?)\s*<\/h2>/i;
          if (!inlineFaqPattern.test(content)) return true;
          const doc = context.document as { faq?: unknown[] } | undefined;
          const faqCount = Array.isArray(doc?.faq) ? doc!.faq!.length : 0;
          if (faqCount === 0) return true;
          return `Content contains an inline "Frequently Asked Questions" H2, AND the FAQ field has ${faqCount} items. The page template renders the FAQ array as its own section, so this article will show the FAQ twice. Either remove the inline H2 (plus its Q&A markup) from Content, or clear the FAQ field.`;
        }),
    }),
    defineField({
      name: 'timeToRead',
      title: 'Time to Read',
      type: 'string',
    }),
    defineField({
      name: 'featured',
      title: 'Featured',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'publishedDate',
      title: 'Published Date',
      type: 'datetime',
    }),
    defineField({
      name: 'lastUpdated',
      title: 'Last Updated',
      type: 'datetime',
    }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'reference',
      to: [{ type: 'teamMember' }],
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: [{ type: 'category' }],
    }),
    defineField({
      name: 'categories',
      title: 'Categories',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'category' }] }],
    }),
    defineField({
      name: 'visuals',
      title: 'Visuals',
      type: 'array',
      description: 'Inline visuals (illustrations, charts, screenshots) generated by the visuals pipeline. Each attaches to a position anchor in the article body.',
      of: [{ type: 'blogVisual' }],
    }),
    defineField({
      name: 'faq',
      title: 'FAQ',
      type: 'array',
      description: 'Frequently asked questions shown as an accordion at the bottom of the post. Auto-generated from content, editable here.',
      of: [
        {
          type: 'object',
          fields: [
            defineField({ name: 'question', title: 'Question', type: 'string', validation: (rule) => rule.required() }),
            defineField({ name: 'answer', title: 'Answer', type: 'text', rows: 3, validation: (rule) => rule.required() }),
          ],
          preview: {
            select: { title: 'question', subtitle: 'answer' },
          },
        },
      ],
    }),
  ],
  preview: {
    select: {
      title: 'name',
      subtitle: 'excerpt',
      media: 'thumbnail',
    },
  },
});
